# .kodiak.toml
version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot", "renovate"]

# if using `update.always`, add dependabot to the blacklist to allow
# dependabot to update and close stale dependency upgrades.
[update]
ignored_usernames = ["dependabot"]


[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"
